easy_admin:
    design:
        menu:
            - label: 'Innolab'
              icon : 'lightbulb'
              children: 
                - {entity: 'User', label: 'Utilisateurs', icon: 'users'}
                - {entity: 'Programmes', label: 'Programmes', icon: 'tasks'}
    entities:
    # List the entity class name you want to manage
        
       - App\Entity\User
       - App\Entity\Programmes
