easy_admin:
        entities:
            User:
                class: App\Entity\User
                templates:
                    edit: 'admin/user/edit.html.twig'
                list:
                  actions:
                      - {name: "edit", icon: "pencil", label: false, css_class: "btn btn-primary mb-2"}
                      - {name: "delete", icon: "trash", label: false, css_class: "btn btn-danger"}